#+title: The DuPont Identity
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

The DuPont Identity breaks Return-on-Equity (ROE) into 3 separate components, the Profit Margin (PM), Total Asset Turnover (TAT) and the Equity Multiplier (EM).

* Derivation

We'll first state /ROE/ in terms of /ROA/ because it gives and important insight for using each as a measure of management performance.  

** The First Step: ROA

Let /NI/ denote Net Income, /E/ denote equity, and /A/ denote assets.  /ROA/ is Return-on-Assets.  

$$ROE = \frac{NI}{E} = \frac{NI}{A}(\frac{A}{E}) = ROA(EM)$$

This is not yet the DuPont Identity, but it does show us something very
useful.  /ROE/ is equal to /ROA/ multiplied by a measure of the firm's
capital structure.  Remember /EM/ is the firm's debt-to-equity ratio plus 1.  

The important point here is managers can change /EM/ easily.  In fact if they
want to increase /EM/ (and thereby likely[fn:1] increase /ROE/) they just have to
issue debt and buy back stock. We will see /ROA/ is solely a function of
operating measure of the firm, and cannot easily be changed by management.

So if you were to measure management performance would you use the measure that management can easily increase or decrease via the capital structure?  Or would you use the measure of operating performace they cannot easily
change?

** DuPont Identity

Decomposing /ROA/:

$$ROA = \frac{NI}{A} = \frac{NI}{S}(\frac{S}{A}) = PM(TAT)$$

where /S/ denotes sales, and /PM/ and /TAT/ is profit margin and total asset turnover respectively.  Inserting this into the /ROE/ equation above affords:

$$ROE = PM(TAT)(EM)$$

which is the DuPont Identity.  It says that a firm's return on equity is the product of the firm's profit margin, total asset turnover, and equity multiplier.  

* Application

This is particularly useful when you realize that profit margin measures a firm's profitability.  That is, it measures how well a firm controls its costs.  Total asset turnover, however, measures how efficiently a firms uses its assets.  Lastly, the equity multiplier (which is one plus the debt-to-equity ratio) is a measure of the firm's use of debt in its capital structure.

So the DuPont Identity allows you to see what is driving a firm's /ROE/.  Does the firm have a high /ROE/ because it controls is costs, or because it uses its assets efficiently?  Or does it simply have a high /ROE/ because it is highly leveraged (not a particularly good reason).

#+BEGIN_QUOTE
Author note:  I once was asked by upper management for an analysis of the performance of our wind farms in north Texas.  While going through their financial statements I realized I had everything I needed to calculate the DuPont Identity.  I was thus able to point to profitability as the driver of our wind farm returns.
#+END_QUOTE


#+BEGIN_EXPORT html

<script>

var calculate = function() {

  var PM = Number(document.getElementById("PM").value);
  var TAT = Number(document.getElementById("TAT").value);
  var DE = Number(document.getElementById("DE").value);

  var roe = PM * TAT * (1 + DE);
  
  document.getElementById("out_roe").innerHTML = roe.toFixed(4);

}

</script>

<body class="all">
  <h3>
    ROE (DuPont) Calculator
  </h3>

  <div class="row">

    <div class="column">
      <table style="width:100%">
        <tr>
          <th align="left">Profit Margin:</th>
          <th><input id="PM" value="0.08" style="width: 50px"></th>
        </tr>
        <tr>
          <th align="left">Total Asset Turnover:</th>
          <th><input id="TAT" value="1.3" style="width: 50px"></th>
        </tr>
        <tr>
          <th align="left">Debt-to-Equity Ratio:</th>
          <th><input id="DE" value="0.5" style="width: 50px"></th>
        </tr>
      </table>
      <button onclick="calculate()">
        Calculate.
      </button>
    </div>

    <div class="column">
    <p><b>ROE: <span id="out_roe"></span></b></p>
    </div>

  </div>
  <br>
  <br>
  <br>
</body>

#+END_EXPORT


 
* Self-Quiz Questions


#+begin_export html
<script>
var submitAnswer1 = function() {

  var radios = document.getElementsByName('choice');
  var val= "";
  for (var i = 0, length = radios.length; i < length; i++) {
      if (radios[i].checked) {
         val = radios[i].value; 
         break;
       }
  }
  
  if (val == "" ) {
   // alert('please select choice answer');
document.getElementById("p1").innerHTML = "Choose your answer.";
document.getElementById("p1").style.backgroundColor = "white";
  } else if ( val == "Correct" ) {
//    alert('Answer is correct !');
document.getElementById("p1").innerHTML = "Correct!";
document.getElementById("p1").style.backgroundColor = "#90EE90";
  } else {
//    alert('Answer is wrong');
document.getElementById("p1").innerHTML = "Wrong";
document.getElementById("p1").style.backgroundColor = "#ff6666";
  }
};
</script>



<p>1. Assume Mohawk Valley Skateboards has a 10% profit margin, 1.6 in total asset turnover, and a 1.75 equity multiplier.  What is the firm's return on equity?</p>
<form >
<input type="radio" name="choice" value="Incorrect"> 4%<br>
<input type="radio" name="choice" value="Correct"> 28%<br>
<input type="radio" name="choice" value="Incorrect"> 36%<br>
<input type="radio" name="choice" value="Incorrect"> 55%
</form>
<button onclick="submitAnswer1()">Submit Answer</button>
<span id="p1"></span>
<br>
#+end_export


#+begin_export html
<script>
var submitAnswer2 = function() {

  var radios = document.getElementsByName('choice2');
  var val= "";
  for (var i = 0, length = radios.length; i < length; i++) {
      if (radios[i].checked) {
         val = radios[i].value; 
         break;
       }
  }
  
  if (val == "" ) {
   // alert('please select choice answer');
document.getElementById("p2").innerHTML = "Choose your answer.";
document.getElementById("p2").style.backgroundColor = "white";
  } else if ( val == "Correct" ) {
//    alert('Answer is correct !');
document.getElementById("p2").innerHTML = "Correct!";
document.getElementById("p2").style.backgroundColor = "#90EE90";
  } else {
//    alert('Answer is wrong');
document.getElementById("p2").innerHTML = "Wrong";
document.getElementById("p2").style.backgroundColor = "#ff6666";
  }
};
</script>


<br>
<p>2. New Hartford Paving Inc has a 10% profit margin, a 30% return on equity, and a debt-to-equity ratio of 1.2?  What is the firm's total asset turnover?</p>
<form >
<input type="radio" name="choice2" value="Incorrect"> 1.36<br>
<input type="radio" name="choice2" value="Incorrect"> 1.77<br>
<input type="radio" name="choice2" value="Correct"> 2.2<br>
<input type="radio" name="choice2" value="Incorrect"> 5.12
</form>
<button onclick="submitAnswer2()">Submit Answer</button>
<span id="p2"></span>
#+end_export

#+begin_export html
<script>
var submitAnswer3 = function() {

  var radios = document.getElementsByName('choice3');
  var val= "";
  for (var i = 0, length = radios.length; i < length; i++) {
      if (radios[i].checked) {
         val = radios[i].value; 
         break;
       }
  }
  
  if (val == "" ) {
   // alert('please select choice answer');
document.getElementById("p3").innerHTML = "Choose your answer.";
document.getElementById("p3").style.backgroundColor = "white";
  } else if ( val == "Correct" ) {
//    alert('Answer is correct !');
document.getElementById("p3").innerHTML = "Correct!";
document.getElementById("p3").style.backgroundColor = "#90EE90";
  } else {
//    alert('Answer is wrong');
document.getElementById("p3").innerHTML = "Wrong";
document.getElementById("p3").style.backgroundColor = "#ff6666";
  }
};
</script>


<br>
<p>3.  If a firm has a 15% return on assets and a debt to equity ratio of 2, what is its return on equity?</p>
<form >
<input type="radio" name="choice3" value="Incorrect"> 15%<br>
<input type="radio" name="choice3" value="Incorrect"> 25%<br>
<input type="radio" name="choice3" value="Incorrect"> 33%<br>
<input type="radio" name="choice3" value="Correct"> 45%
</form>
<button onclick="submitAnswer3()">Submit Answer</button>
<span id="p3"></span>
#+end_export

* [[https://en.wikipedia.org/wiki/Flesch%25E2%2580%2593Kincaid_readability_tests][Reading Ease Score]]

#+BEGIN_SRC elisp :results output :exports results
(print (writegood-reading-ease))
#+END_SRC

#+RESULTS:
: 
: "Flesch-Kincaid reading ease score: 76.49 Fairly easy (7th grade)"

#+BEGIN_SRC elisp :results output :exports results
(print (writegood-grade-level))
#+END_SRC

#+RESULTS:
: 
: "Flesch-Kincaid grade level score: 4.88"

* Footnotes

[fn:1] There are unlikely situations where increasing a firm's /EM/ will decrease /ROE/ because the effect of interest expense on reducing /PM/ more than offsets the increase in the debt-to-equity ratio.

